config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :contacts
  resources :events
  root 'contacts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  include PgSearch::Model

  has_many :emails, inverse_of: :contact, dependent: :destroy
  has_many :phone_numbers, inverse_of: :contact, dependent: :destroy
  has_many :relationships, inverse_of: :contact, dependent: :destroy

  accepts_nested_attributes_for :emails, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :phone_numbers, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :relationships, allow_destroy: true, reject_if: :all_blank

  validates :full_name, presence: true

  scope :sorted, -> { order('full_name ASC') }

  pg_search_scope :search_for,
                  associated_against: {
                    emails: %i[email],
                    phone_numbers: %i[phone_number]
                  },
                  against: %i[full_name organization notes],
                  order_within_rank: 'contacts.full_name ASC'

  def primary_email
    return unless emails.present?

    if emails.find_by(label: 'Email')
      emails.find_by(label: 'Email').email
    else
      emails.first.email
    end
  end

  def primary_phone_number
    return unless phone_numbers.present?

    if phone_numbers.find_by(label: 'Phone')
      phone_numbers.find_by(label: 'Phone').phone_number
    else
      phone_numbers.first.phone_number
    end
  end
end

app/models/email.rb
# frozen_string_literal: true

class Email < ApplicationRecord
  belongs_to :contact
  LABELS = %w[Email Home Work Other].freeze

  validates :email, presence: true
  validates :label, inclusion: { in: LABELS, message: 'Invalid Label' }
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :rsvps, dependent: :destroy
  has_many :contacts, through: :rsvps, source: :contact

  accepts_nested_attributes_for :rsvps, allow_destroy: true, reject_if: :all_blank

  validates :name, :date, presence: true
  validates :attendees, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate  :date_cannot_be_in_past

  def available
    count = rsvps.where(rsvp: true).count
    attendees < count ? 0 : attendees - count
  end

  private

  def date_cannot_be_in_past
    errors.add(:date, "can't be in the past") if date.present? && date < Date.today
  end
end

app/models/phone_number.rb
# frozen_string_literal: true

class PhoneNumber < ApplicationRecord
  belongs_to :contact
  LABELS = %w[Phone Home Work Other Mobile Main Fax Pager].freeze

  validates :phone_number, presence: true
  validates :label, inclusion: { in: LABELS, message: 'Invalid Label' }
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :person, class_name: 'Contact'
  belongs_to :contact, class_name: 'Contact'

  TAGS = %w[Spouse Child Mother Father Parent Brother Sister Friend Relative Manager Partner].freeze

  validates :person, presence: true
  validates :tag, inclusion: { in: TAGS, message: 'Invalid Tag' }
end

app/models/rsvp.rb
# frozen_string_literal: true

class Rsvp < ApplicationRecord
  belongs_to :contact
  belongs_to :event
  validates :rsvp, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  def index
    if params[:search]&.present?
      @contacts = Contact.search_for(params[:search])
      render :search
    else
      @contacts = Contact.sorted
    end
  end

  def show; end

  def new
    @contact = Contact.new
    @contact.emails.build
    @contact.phone_numbers.build
    @contact.relationships.build
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contacts_path, notice: 'Contact created successfully!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Contact updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path, notice: 'Contact deleted successfully!'
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact)
          .permit(:full_name, :organization, :notes, emails_attributes: %i[id label email _destroy],
                                                     phone_numbers_attributes: %i[id label phone_number _destroy],
                                                     relationships_attributes: %i[id tag person_id _destroy])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @events = Event.order('date')
  end

  def show
    @positives = @event.rsvps.where(rsvp: true)
    @negatives = @event.rsvps.where(rsvp: false)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path, notice: 'Event created successfully!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'Event deleted successfully!'
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :date, :attendees, rsvps_attributes: %i[id rsvp contact_id _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
  def contact_image(contact, **args)
    url = "https://avatars.dicebear.com/api/initials/#{contact.full_name}.svg?options[bold]=1"
    image_tag(url, alt: contact.full_name, **args)
  end
end

app/helpers/event_helper.rb
# frozen_string_literal: true

module EventHelper
  def date_in_words(event)
    "starts in #{distance_of_time_in_words Time.now, event.date}"
  end
end

app/views/contacts/_email_fields.html.erb
<div class="flex items-center justify-between h-12 p-4 mx-2 my-4 border border-gray-100 rounded-lg shadow nested-fields">
  <div class="flex items-center w-full">
    <%= f.select :label, Email::LABELS, {}, class: "font-semibold text-gray-600" %>
    <%= f.email_field :email, class: "mx-4 w-full text-gray-800" %>
  </div>
  <%= render partial: 'shared/errors', locals: { collection: @contact, error: 'emails.email' } %>
  <%= link_to_remove_association f, class: "flex items-center justify-center p-2 bg-red-400 rounded-full shadow-md hover:bg-red-500" do %>
    <svg class="w-4 h-4 text-white toggle__lock" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
    </svg>
  <% end %>
</div>

app/views/contacts/_form.html.erb
<div class="p-8 bg-white md:rounded-lg md:shadow-md">
  <%= form_with(model: @contact, local: true) do |f| %>
    <div class="grid gap-6 lg:grid-cols-2">
      <div>
        <div class="relative p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
          <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
            <p><%= f.label :full_name, class: "px-1 text-gray-600 bg-white" %></p>
          </div>
          <p>
            <%= f.text_field :full_name, autofocus: true, autocomplete: false, class: "block w-full h-full px-2 py-1 text-gray-900 outline-none", tabindex: 0 %>
          </p>
        </div>
        <%= render partial: 'shared/errors', locals: { collection: @contact, error: :full_name } %>
      </div>
      <div class="relative p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
        <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
          <p><%= f.label :organization, class: "px-1 text-gray-600 bg-white" %></p>
        </div>
        <p><%= f.text_field :organization, autocomplete: false, class: "block w-full h-full px-2 py-1 text-gray-900 outline-none", tabindex: 0 %></p>
      </div>
    </div>
    <div class="flex flex-col my-10 lg:flex-row">
      <div class="w-full lg:mr-3 lg:w-1/2">
        <div class="relative p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500" >
          <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
            <p class="px-1 text-gray-600 bg-white">Emails</p>
          </div>
          <div id="emails_field">
            <%= f.fields_for :emails do |e| %>
              <% render 'email_fields', f: e %>
            <% end %>
          </div>
          <div class="flex items-center justify-center h-12 p-4 mx-2 my-4 bg-gray-200 rounded-lg shadow-inner">
            <%= link_to_add_association f, :emails, class: "flex items-center px-2 py-1 border border-gray-400 border-dashed rounded cursor-pointer", data: { association_insertion_node: '#emails_field', association_insertion_method: :append } do %>
              <div>
                <%= inline_svg_tag "plus.svg" %>
              </div>
              <div class="mx-1 font-medium text-gray-500">Add an Email</div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="w-full mt-10 lg:ml-3 lg:w-1/2 lg:mt-0">
        <div class="relative p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
          <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
            <p class="px-1 text-gray-600 bg-white">Phone Numbers</p>
          </div>
          <div id="phones_field">
            <%= f.fields_for :phone_numbers do |p| %>
              <% render 'phone_number_fields', f: p %>
            <% end %>
          </div>
          <div class="flex items-center justify-center h-12 p-4 mx-2 my-4 bg-gray-200 rounded-lg shadow-inner">
            <%= link_to_add_association f, :phone_numbers, class: "flex items-center px-2 py-1 border border-gray-400 border-dashed rounded cursor-pointer", data: { association_insertion_node: '#phones_field', association_insertion_method: :append } do %>
              <div>
                <%= inline_svg_tag "plus.svg" %>
              </div>
              <div class="mx-1 font-medium text-gray-500">Add a Phone Number</div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="flex flex-col my-10 lg:flex-row">
      <div class="w-full lg:mr-3 lg:w-1/2">
        <div class="relative p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500" >
          <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
            <p class="px-1 text-gray-600 bg-white">Relationships</p>
          </div>
          <div id="relationships_field">
            <%= f.fields_for :relationships do |r| %>
              <% render 'relationship_fields', f: r %>
            <% end %>
          </div>
          <div class="flex items-center justify-center h-12 p-4 mx-2 my-4 bg-gray-200 rounded-lg shadow-inner">
            <%= link_to_add_association f, :relationships, class: "flex items-center px-2 py-1 border border-gray-400 border-dashed rounded cursor-pointer", data: { association_insertion_node: '#relationships_field', association_insertion_method: :append } do %>
              <div>
                <%= inline_svg_tag "plus.svg" %>
              </div>
              <div class="mx-1 font-medium text-gray-500">Add a Relationship</div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="w-full lg:ml-3 lg:w-1/2">
        <div class="relative p-1 py-2 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
          <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
            <p><%= f.label :notes, class: "px-1 text-gray-600 bg-white" %></p>
          </div>
          <p>
            <%= f.text_area :notes, rows: 4, class: "notes block w-full h-full p-2 text-gray-900 outline-none", tabindex: 0 %>
          </p>
        </div>
      </div>
    </div>
    <div class="pt-3 mt-6 text-center border-t">
      <%= link_to "Cancel", :back, class: "border border-transparent hover:border-gray-400 px-3 py-1 rounded" %>
      <%= f.submit "Save Contact", class: "px-3 py-1 text-gray-100 transition-all duration-300 bg-purple-600 rounded hover:shadow-inner hover:bg-purple-700 cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/contacts/edit.html.erb
<div class="flex items-center mb-3 ml-3 lg:ml-0">
  <%= inline_svg_tag "edit-contact.svg", class: "w-12 h-12" %>
  <h1 class="ml-4 text-3xl font-bold text-black">Edit Contact: <%= @contact.full_name %></h1>
</div>
<%= render "form", contact: @contact %>

app/views/contacts/index.html.erb
<div class="flex items-center">
  <%= inline_svg_tag "contacts.svg", class: "h-12 w-12 mr-2 -ml-1" %>
  <h1 class="mx-2 text-3xl font-bold lg:mx-0">My Contacts</h1>
</div>
<div class="flex mx-2 mt-3 mb-5 lg:mx-0">
  <%= form_tag contacts_path, method: :get, class: "flex w-full px-4 py-2 bg-gray-800 rounded focus-within:bg-gray-700" do %>
    <%= search_field_tag :search, params[:search], placeholder: "Search", 'aria-label': "Search", class: "w-full text-sm leading-tight text-gray-100 placeholder-gray-200 bg-gray-800 focus:outline-none focus:bg-gray-700" %>
    <%= button_tag type: :submit, name: nil do %>
      <%= inline_svg_tag "search.svg", class: "w-8 h-8" %>
    <% end %>
  <% end %>
  <%= link_to new_contact_path, class: "create-contact ml-2 p-2 text-center rounded-md" do %>
    <span>Add New Contact</span>
  <% end %>
</div>
<div class="flex flex-col h-full mx-2 mt-2 bg-white border border-gray-800 rounded-md lg:mx-0">
  <% @contacts.each do |contact| %>
    <div class="flex items-center justify-between border-b border-gray-800 last:border-b-0">
      <%= link_to contact, class: "flex items-center p-4 w-full" do %>
        <%= contact_image contact, class: "w-8 h-8 rounded-md"%>
        <h1 class="ml-4 text-black"><%= contact.full_name %></h1>
      <% end %>
      <%= link_to edit_contact_path(contact) do %>
        <%= inline_svg_tag "edit.svg", class: "h-8 w-8 m-4 bg-gray-300 hover:bg-gray-400 rounded" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/contacts/search.html.erb
<h1 class="text-3xl font-bold">Search Results</h1>
<div class="flex my-3">
  <%= form_tag contacts_path, method: :get, class: "flex w-full px-4 py-2 bg-gray-800 rounded focus-within:bg-gray-700" do %>
    <%= text_field_tag :search, params[:search], class: "w-full text-sm leading-tight text-gray-100 placeholder-gray-200 bg-gray-800 focus:outline-none focus:bg-gray-700" %>
    <%= button_tag type: :submit, name: nil do %>
      <%= inline_svg_tag "search.svg", class: "w-8 h-8" %>
    <% end %>
  <% end %>
  <%= link_to "Add New Contact", new_contact_path, class: "ml-2 bg-gray-700 hover:bg-gray-800 rounded text-white p-2 text-center" %>
</div>
<div class="mt-5 overflow-hidden border-b border-gray-200 shadow sm:rounded-lg">
  <table class="min-w-full divide-y divide-gray-200">
    <thead>
      <tr>
        <th class="px-4 py-3 text-sm leading-4 tracking-wider text-left text-gray-500 uppercase bg-gray-100">Full Name</th>
        <th class="px-4 py-3 text-sm leading-4 tracking-wider text-left text-gray-500 uppercase bg-gray-100">Email Address</th>
        <th class="px-4 py-3 text-sm leading-4 tracking-wider text-left text-gray-500 uppercase bg-gray-100">Phone Number</th>
        <th class="px-4 py-3 text-sm leading-4 tracking-wider text-left text-gray-500 uppercase bg-gray-100">Organization</th>
        <th class="px-4 py-3 bg-gray-100"></th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      <% if @contacts.each do |contact| %>
        <tr>
          <td class="px-6 py-4 whitespace-no-wrap">
            <%= link_to contact, class: "flex items-center w-full" do %>
              <%= contact_image contact, class: "w-10 h-10 rounded-md"%>
              <span class="ml-4"><%= contact.full_name %></span>
            <% end %>
          </td>
          <td class="px-6 py-4 whitespace-no-wrap "><%= contact.primary_email %></td>
          <td class="px-6 py-4 whitespace-no-wrap"><%= number_to_phone contact.primary_phone_number %></td>
          <td class="px-6 py-4 whitespace-no-wrap"><%= contact.organization if contact.organization.present? %></td>
          <td class="px-6 py-4 whitespace-no-wrap">
            <div class="flex items-center justify-end">
              <%= link_to contact_path(contact) do %>
                <%= inline_svg_tag "contact.svg", class: "h-8 w-8 mr-1 bg-purple-200 hover:bg-purple-300 rounded" %>
              <% end %>
              <%= link_to edit_contact_path(contact) do %>
                <%= inline_svg_tag "edit.svg", class: "h-8 w-8 mx-1 bg-gray-300 hover:bg-gray-400 rounded" %>
              <% end %>
              <%= link_to contact, method: :delete do %>
                <%= inline_svg_tag "trash.svg", class: "h-8 w-8 ml-1 bg-red-200 hover:bg-red-300 rounded" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end.empty? %>
        <tr>
          <td colspan="5" class="p-5 whitespace-no-wrap">
            <div class="flex items-center justify-center">
              <%= inline_svg_tag "not-found.svg", class: "w-6 h-6 mr-3" %>
              No Contacts Found
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/show.html.erb
<div class="flex flex-col items-center justify-between lg:flex-row">
  <div class="flex items-center">
    <%= contact_image @contact, class: "w-16 h-16 rounded-md"%>
    <h1 class="ml-4 text-3xl font-bold"><%= @contact.full_name %></h1>
  </div>
  <div class="flex mt-4 lg:mt-0">
    <%= link_to edit_contact_path @contact do %>
      <%= inline_svg_tag "edit.svg", class: "mr-2 w-10 h-10 bg-gray-100 rounded hover:bg-gray-400"%>
    <% end %>
    <%= link_to @contact, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= inline_svg_tag "trash.svg", class: "w-10 h-10 bg-red-100 hover:bg-red-200 rounded"%>
    <% end %>
  </div>
</div>
<div class="p-8 mt-4 bg-white md:rounded-lg md:shadow-md">
  <div class="relative p-2 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
    <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
      <p class="px-1 text-gray-600 bg-white">Organization</p>
    </div>
    <p class="block w-full h-full px-2 py-1 text-gray-900 outline-none"><%= @contact.organization %></p>
  </div>
  <div class="flex flex-col my-10 lg:flex-row">
    <div class="w-full lg:mr-4 lg:w-1/2">
      <div class="relative h-full p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500" >
        <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
          <p class="px-1 text-gray-600 bg-white">Emails</p>
        </div>
        <div class="grid items-center w-full grid-cols-6 p-2">
          <% @contact.emails.each do |e| %>
            <div class="col-span-1 py-1 font-semibold">
              <%= e.label %>
            </div>
            <div class="col-span-5 py-1">
              <%= e.email %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="w-full mt-10 lg:ml-4 lg:w-1/2 lg:mt-0">
      <div class="relative h-full p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
        <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
          <p class="px-1 text-gray-600 bg-white">Phone Numbers</p>
        </div>
        <div class="grid items-center w-full grid-cols-6 p-2">
          <% @contact.phone_numbers.each do |p| %>
            <div class="col-span-1 py-1 font-semibold ">
              <%= p.label %>
            </div>
            <div class="col-span-5 py-1">
              <%= number_to_phone p.phone_number, area_code: true %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="flex flex-col mt-10 lg:flex-row">
    <div class="w-full lg:mr-4 lg:w-1/2">
      <div class="relative h-full p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500" >
        <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
          <p class="px-1 text-gray-600 bg-white">Relationships</p>
        </div>
        <div class="grid items-center w-full grid-cols-6 p-2">
          <% @contact.relationships.each do |r| %>
            <div class="py-1 col-span-full">
              <%= link_to "#{r.person.full_name}' ", contact_path(r.person), class: "hover:border-b-2" %>
              <span class="font-semibold"><%= r.tag %></span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="w-full mt-10 lg:ml-4 lg:w-1/2 lg:mt-0">
      <div class="relative p-1 py-2 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
        <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
          <p class="px-1 text-gray-600 bg-white">Notes</p>
        </div>
        <p class="w-full p-2"><%= @contact.notes %></p>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="flex items-center justify-between pt-4 pb-2">
  <div class="flex items-center">
    <%= inline_svg_tag "event.svg", class: "h-12 w-12 mr-2 -ml-1" %>
    <h1 class="mx-2 text-3xl font-bold lg:mx-0">My Events</h1>
  </div>
  <%= link_to new_event_path, class: "create-event px-4 py-3 rounded-md" do %>
    <span>Create New Event</span>
  <% end %>
</div>
<div class="flex flex-col h-full mx-2 mt-2 rounded lg:mx-0">
  <% @events.each do |event| %>
    <div class="flex items-center justify-between my-1 bg-white border border-gray-800 rounded-md">
      <%= link_to event, class: "flex items-center p-4 w-full" do %>
        <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/5">
          <p class="mb-1 ml-4 text-lg font-semibold text-black"><%= event.name %></p>
          <p class="ml-4 text-black"><%= date_in_words event %></p>
        </div>
        <p class="py-4 pl-8 ml-6 lg:border-gray-500 lg:border-l-2">
          <span class="p-1 px-2 mr-2 font-bold bg-purple-300 rounded"><%= event.available %></span>
          open spots
        </p>
      <% end %>
      <%= link_to edit_event_path(event) do %>
        <%= inline_svg_tag "edit.svg", class: "h-8 w-8 m-4 bg-gray-300 hover:bg-gray-400 rounded" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="flex flex-col items-center justify-between lg:flex-row">
  <div class="flex items-center">
    <%= inline_svg_tag "event.svg", class: "w-16 h-16 rounded-md"%>
    <h1 class="ml-4 text-3xl font-bold"><%= @event.name %></h1>
  </div>
  <div class="flex mt-4 lg:mt-0">
    <%= link_to edit_event_path @event do %>
      <%= inline_svg_tag "edit.svg", class: "mr-2 w-10 h-10 bg-gray-100 rounded hover:bg-gray-400"%>
    <% end %>
    <%= link_to @event, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= inline_svg_tag "trash.svg", class: "w-10 h-10 bg-red-100 rounded hover:bg-red-200"%>
    <% end %>
  </div>
</div>
<div class="p-8 mt-4 bg-white md:rounded-lg md:shadow-md">
  <div class="flex">
    <div class="relative w-1/2 mr-4 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
      <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
        <p class="px-1 text-gray-600 bg-white">Event Date</p>
      </div>
      <p class="block w-full h-full p-2 text-center text-gray-900 outline-none"><%= time_tag @event.date %></p>
    </div>
    <div class="relative w-1/2 ml-4 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
      <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
        <p class="px-1 text-gray-600 bg-white">Number of Attendees</p>
      </div>
      <p class="block w-full h-full p-2 text-center text-gray-900 outline-none"><%= @event.attendees %></p>
    </div>
  </div>
  <div class="flex flex-col mt-10 lg:flex-row">
    <div class="w-full lg:mr-4 lg:w-1/2">
      <div class="relative h-full p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500" >
        <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
          <p class="px-2 text-white bg-green-500 rounded">Attendees Going</p>
        </div>
        <div class="flex flex-col py-2">
          <% @positives.each do |r| %>
            <div class="w-full p-2 text-center">
              <%= link_to r.contact.full_name, r.contact, class: "hover:border-b-2" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="w-full mt-10 lg:ml-4 lg:w-1/2 lg:mt-0">
      <div class="relative h-full p-1 transition-all duration-500 border rounded focus-within:border-blue-500 focus-within:text-blue-500">
        <div class="absolute px-1 -mt-4 text-xs tracking-wider uppercase">
          <p class="px-2 text-white bg-red-500 rounded">Attendees Missing Out</p>
        </div>
        <div class="flex flex-col py-2">
          <% @negatives.each do |r| %>
            <div class="w-full p-2 text-center">
              <%= link_to r.contact.full_name, r.contact, class: "hover:border-b-2" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>